# Generated by Django 4.1.5 on 2023-01-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='listing_owner',
        ),
    ]
